MISSED_DAY_PENALTY = 10
FAILED_WORDLE_SCORE = 7
WORDLE_GRID_WIDTH = 5
MAX_WORDLE_ATTEMPTS = 6

# Season status constants
STATUS_ACTIVE = 'active'
STATUS_COMPLETED = 'completed'
STATUS_CANCELLED = 'cancelled'
